### ISSUE TITLE
openldap wont start

### ISSUE THREAD

**Issue by psychomantys** [seaweedfs/seaweedfs-csi-driver#162]
I'm trying to use the openldap helm chart with a seaweed volume, but the ldap server is not starting. I've checked the logs and seen that the helm chart is successfully installed and configured, but the ldap server is not being started. The strange thing is that when I use a volume that's not from seaweed, the LDAP server starts without any issues.

I'm starting to think that the issue might be related to the seaweedfs volume, perhaps with the way the mdb is being used on top of the volume. However, I can't seem to find any logs or references that point to the root cause of the problem.

Has anyone else encountered this issue? Any help would be greatly appreciated.

Here are the logs from the LDAP server:

```
660e3a1e.3ad9cf10 0x7fd057985740 >>> dnNormalize: <cn=Uptime>
660e3a1e.3ad9db22 0x7fd057985740 <<< dnNormalize: <cn=uptime>
660e3a1e.3ad9f698 0x7fd057985740 >>> dnNormalize: <cn=Read>
660e3a1e.3ada01e2 0x7fd057985740 <<< dnNormalize: <cn=read>
660e3a1e.3ada1538 0x7fd057985740 >>> dnNormalize: <cn=Write>
660e3a1e.3ada1e20 0x7fd057985740 <<< dnNormalize: <cn=write>
660e3a1e.3ada31f8 0x7fd057985740 backend_startup_one: starting "dc=my-domain,dc=com"
660e3a1e.3ada3a05 0x7fd057985740 mdb_db_open: "dc=my-domain,dc=com"
660e3a1e.3add4a58 0x7fd057985740 mdb_db_open: database "dc=my-domain,dc=com": dbenv_open(/bitnami/openldap/data).
```

And here are the kustomize with the values.yaml for the helm chart of ldap:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: openldap-stack-ha
    name: openldap-stack-ha
    version: 4.2.2
    repo: 'https://jp-gouin.github.io/helm-openldap/'
    includeCRDs: true
    namespace: openldap
    valuesInline:
      global:
        existingSecret: openldap-secret
        adminUser: ldapadmin
        configUser: ldapadminconfig
      env:
        LDAP_LOGLEVEL: "-1"
      persistence:
        enabled: true
      podAntiAffinityPreset: soft
```
