### ISSUE TITLE
seaweedfs storageclass IOPS too low

### ISSUE THREAD

**Issue by ankitjilka** [seaweedfs/seaweedfs-csi-driver#165]
- I deployed seaweedfs storageclass using helm chart in my Kubernetes cluster. and I make volume which is used seaweedfs as storageclass  and when I measure IOPS using fio . so that IOPS are too low compare to longhorn and local-path storageclass

- storageclass configuration
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: seaweedfs-csi
    meta.helm.sh/release-namespace: seaweedfs
  labels:
    app.kubernetes.io/managed-by: Helm
  name: seaweedfs-storage
provisioner: seaweedfs-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
