### ISSUE TITLE
When used in k8s, only one PVC can be written at a time

### ISSUE THREAD

**Issue by god12311** [seaweedfs/seaweedfs-csi-driver#178]
1、Seaweedfs deployed outside the cluster is connected to k8s
The seaweedfs-csi.yaml file has been changed to use an externally deployed seaweedfs cluster；All the information related to SEAWEEDFS_FILER has been changed
env:
```
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: SEAWEEDFS_FILER
              #value: "SEAWEEDFS_FILER:8888"
              #value: "192.168.27.171:8888,192.168.27.172:8888,192.168.27.173:8888"
              value: "192.168.27.173:8888"
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DRIVER_NAME
              value: "seaweedfs-csi-driver"
```

2、Through the sample deployment test, it can be read and written after mounting，For example：my-csi-app2
```
# kubectl  get pod 
NAME                                    READY   STATUS    RESTARTS   AGE
my-csi-app                              1/1     Running   0          7m22s
my-csi-app2                             1/1     Running   0          8m15s
seaweedfs-controller-79c7dcbf4c-q7hv7   5/5     Running   0          4h35m
seaweedfs-node-g5v2r                    3/3     Running   0          4h35m
seaweedfs-node-k95kz                    3/3     Running   0          4h35m
seaweedfs-node-kckhf                    3/3     Running   0          4h35m
seaweedfs-node-ncwjt                    3/3     Running   0          4h35m
# kubectl  exec -it my-csi-app2 -- sh 
/ # df -h 
Filesystem                Size      Used Available Use% Mounted on
overlay                  97.0G     23.9G     73.1G  25% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
192.168.27.173:8888:/buckets/pvc-4630d22e-df87-4b35-9bbd-62ce7a2ae0c3
                          5.0G         0      5.0G   0% /data
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /dev/termination-log
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /etc/resolv.conf
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /etc/hostname
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     7.7G     12.0K      7.7G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.9G         0      3.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.9G         0      3.9G   0% /proc/scsi
tmpfs                     3.9G         0      3.9G   0% /sys/firmware
/ # cd /data
/data # echo "my-csi-app2" > my-csi-app2.txt
/data # cat my-csi-app2.txt 
my-csi-app2
```

3、For example: my-csi-app cant write ；But the file name can be created，The creation command will hang for about 10 seconds before the filename is created.
```
# kubectl  exec -it my-csi-app -- sh 
/ # df -h 
Filesystem                Size      Used Available Use% Mounted on
overlay                  97.0G     23.9G     73.1G  25% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.9G         0      3.9G   0% /sys/fs/cgroup
192.168.27.173:8888:/buckets/pvc-3239bab8-0cd8-4c09-8522-b91a39035806
                          5.0G         0      5.0G   0% /data
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /dev/termination-log
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /etc/resolv.conf
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /etc/hostname
/dev/mapper/centos-root
                         97.0G     23.9G     73.1G  25% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     7.7G     12.0K      7.7G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.9G         0      3.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.9G         0      3.9G   0% /proc/scsi
tmpfs                     3.9G         0      3.9G   0% /sys/firmware
/ # cd /data
/data # ls
0822
/data # echo "my-csi-app" > my-csi-app.txt
/data # cat my-csi-app.txt
/data # ls
0822            my-csi-app.txt
```

4、The configuration files of the two pods are as follows

my-csi-app2: Create first，can write

```
# cat sample-seaweedfs-pvc2.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-csi-pvc2
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # This value is enforced after 2022/03/18
  storageClassName: seaweedfs-storage

# cat sample-busybox-pod2.yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app2
spec:
  containers:
    - name: my-frontend2
      image: busybox:1.28
      volumeMounts:
        - mountPath: "/data"
          name: seaweedfs-volume2
      command: [ "sleep", "1000000" ]
  volumes:
    - name: seaweedfs-volume2
      persistentVolumeClaim:
        claimName: seaweedfs-csi-pvc2

##################################################
my-csi-app:

# cat sample-seaweedfs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-csi-pvc
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # This value is enforced after 2022/03/18
  storageClassName: seaweedfs-storage

# cat sample-busybox-pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox:1.28
      volumeMounts:
        - mountPath: "/data"
          name: seaweedfs-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: seaweedfs-volume
      persistentVolumeClaim:
        claimName: seaweedfs-csi-pvc
```
