### ISSUE TITLE
The `collection` parameter in StorageClass does not take effect

### ISSUE THREAD

**Issue by hanxiantao** [seaweedfs/seaweedfs-csi-driver#188]
### Issue Description
According to the documentation, I understand that when the `collection` parameter is specified in the StorageClass, it should be mapped to the bucket configured by the `collection`.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mycollection-seaweedfs-storage
provisioner: seaweedfs-csi-driver
parameters:
  collection: mycollection
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
However, after my attempt, it did not execute as expected. It was still mapped to the default-generated `/buckets/<volume-id>`.

I checked the code and tried to configure the `path` parameter. After that, the mapped bucket was changed to the one specified in the `path`.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mycollection-seaweedfs-storage
provisioner: seaweedfs-csi-driver
parameters:
  collection: mycollection
  path: /buckets/lgwtest03
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

![Image](https://github.com/user-attachments/assets/42f25b3e-f23c-4c4e-8ad0-fabbba1c0005)

I initially think there is a problem with the code here. When the `collection` parameter is specified, it should affect the value of `path`, `path = fmt.Sprintf("/buckets/%s", collection)`
https://github.com/seaweedfs/seaweedfs-csi-driver/blob/c4af3d29895c8eeee4b7faf00b05b5792a3976aa/pkg/driver/mounter.go#L37C1-L49C2
