### ISSUE TITLE
Input output error 

### ISSUE THREAD

**Issue by bmgeek** [seaweedfs/seaweedfs-csi-driver#30]
Hello!

I make PV:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-csi-pvc
  namespace: sre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # In case of EP, this value does not have any effect
  storageClassName: seaweedfs-storage
```

and pod for tests:

```
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
  namespace: sre
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: seaweedfs-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: seaweedfs-volume
      persistentVolumeClaim:
        claimName: seaweedfs-csi-pvc
```

I can download file with curl / browser, but can't read this file from pod or can't save data to file from pod.

<img width="849" alt="Снимок экрана 2021-07-21 в 13 26 22" src="https://user-images.githubusercontent.com/67244556/126474343-acaad396-b297-423d-a937-75c6af8d7d27.png">

<img width="532" alt="Снимок экрана 2021-07-21 в 13 28 40" src="https://user-images.githubusercontent.com/67244556/126474653-80afe948-acca-4fb2-858d-1342d57e5e70.png">

I'm search anything in seaweedfs logs, but they are empty
